// Fill out your copyright notice in the Description page of Project Settings.

#include "HUD/EndOverlay.h"
#include "Components/TextBlock.h"
#include "Components/Button.h"
#include "HUD/SFHUD.h"
#include "HUD/StartOverlay.h"

// ================================
// UEndOverlay
// ゲ`ムK了画面のI理クラス
// Class handling the game end screen logic
// ================================

// ウィジェットBrの初期化
// Initialize when widget is constructed
void UEndOverlay::NativeConstruct()
{
    // メインメニュ`ボタンが有郡胜楗リックイベントをバインド
    // Bind click event if the Main Menu button is valid
    if (MainMenuButton)
    {
        MainMenuButton->OnClicked.AddDynamic(this, &UEndOverlay::PressMainMenuButton);
    }
}

// ベストスコアをO定
// Set the best score text
void UEndOverlay::SetBestScore(int32 BestScore)
{
    if (BestScoreText)
    {
        BestScoreText->SetText(FText::FromString(FString::Printf(TEXT("Best Score: %d"), BestScore)));
    }
}

// F在のスコアをO定
// Set the current score text
void UEndOverlay::SetCurrentScore(int32 CurrentScore)
{
    if (CurrenScoreText)
    {
        CurrenScoreText->SetText(FText::FromString(FString::Printf(TEXT("%d"), CurrentScore)));
    }
}

// コインスコアをO定
// Set the collected coin score text
void UEndOverlay::SetCoinScore(int32 CointScore)
{
    if (CoinText)
    {
        CoinText->SetText(FText::FromString(FString::Printf(TEXT("Collected Coin: %d"), CointScore)));
    }
}

// パフォ`マンススコアをO定
// Set the performance score text
void UEndOverlay::SetPerformanceScore(int32 PerformanceScore)
{
    if (PerformanceText)
    {
        PerformanceText->SetText(FText::FromString(FString::Printf(TEXT("Performance Score: %d"), PerformanceScore)));
    }
}

// 距xスコアをO定
// Set the distance score text
void UEndOverlay::SetDistancetScore(int32 DistanceScore)
{
    if (DistanceText)
    {
        DistanceText->SetText(FText::FromString(FString::Printf(TEXT("Distance: %d Metre"), DistanceScore)));
    }
}

// メインメニュ`にるボタンが押されたrのI理
// Handle the event when Main Menu button is pressed
void UEndOverlay::PressMainMenuButton()
{
    // F在の HUD を取得して、スタ`ト画面を表示
    // Get current HUD and show the start overlay
    if (ASFHUD* SFHUD = Cast<ASFHUD>(GetWorld()->GetFirstPlayerController()->GetHUD()))
    {
        this->RemoveFromParent();
        SFHUD->OnOffStartOverlay(true);
    }
}
