// Fill out your copyright notice in the Description page of Project Settings.

#include "HUD/PauseOverlay.h"
#include "Components/Button.h"
#include "Input/KixPlayerController.h"
#include "HUD/SFHUD.h"
#include "HUD/EndOverlay.h"
#include "Characters/Kix/CharactersKix.h"

// ================================
// UPauseOverlay
// ポ`ズメニュ`のg装
// Implementation for pause menu overlay
// ================================

// ウィジェット初期化：ボタンにイベントをバインド
// Initialize widget: bind buttons
void UPauseOverlay::NativeConstruct()
{
    if (ResumeButton)
    {
        ResumeButton->OnClicked.AddDynamic(this, &UPauseOverlay::ResumeButtonClicked);
    }
    if (MainMenuButton)
    {
        MainMenuButton->OnClicked.AddDynamic(this, &UPauseOverlay::EndButtonClicked);
    }
}

// 再_ボタン押下r：ポ`ズを解除してHUD状Bをリセット
// Handle Resume button click: unpause game and reset HUD state
void UPauseOverlay::ResumeButtonClicked()
{
    if (GetWorld())
    {
        APlayerController* PlayerController = GetWorld()->GetFirstPlayerController();
        if (PlayerController)
        {
            PlayerController->SetPause(false);
            PlayerController->SetShowMouseCursor(false);
            this->RemoveFromParent();

            // コントロ`ラのポ`ズ状Bを初期化
            AKixPlayerController* KixController = Cast<AKixPlayerController>(PlayerController);
            if (KixController)
            {
                KixController->SetPauseBoolFalse();
            }
        }
    }
}

// メインメニュ`ボタン押下r：エンドメニュ`を表示してスコアをO定
// Handle Main Menu button click: show end overlay and set scores
void UPauseOverlay::EndButtonClicked()
{
    if (GetWorld())
    {
        APlayerController* PlayerController = GetWorld()->GetFirstPlayerController();
        if (PlayerController)
        {
            ASFHUD* SFHUD = Cast<ASFHUD>(PlayerController->GetHUD());
            if (SFHUD)
            {
                // エンドメニュ`を表示
                SFHUD->OnOffEndOverlay(true);
                EndOverlay = SFHUD->GetEndOverlay();

                if (EndOverlay)
                {
                    // F在のスコア情螭蛟O定
                    ACharactersKix* CharacterKix = Cast<ACharactersKix>(PlayerController->GetPawn());
                    EndOverlay->SetBestScore(CharacterKix->GetPlayerCurrentScore());
                    EndOverlay->SetCurrentScore(CharacterKix->GetPlayerCurrentScore());
                    EndOverlay->SetCoinScore(CharacterKix->GetPlayerCoinScoreScore());
                    EndOverlay->SetPerformanceScore(CharacterKix->GetPlayerPerformanceScore());
                    EndOverlay->SetDistancetScore(CharacterKix->GetPlayerDistanceScore());
                }

                // ポ`ズオ`バ`レイを]じる
                this->RemoveFromParent();
            }
        }
    }
}
