// Fill out your copyright notice in the Description page of Project Settings.

#include "HUD/StartOverlay.h"
#include "Components/Button.h"
#include "Kismet/GameplayStatics.h"
#include "Characters/Kix/CharactersKix.h"

// ================================
// UStartOverlay
// ゲ`ム_始画面のg装
// Implementation for the start screen UI
// ================================

// ボタンにイベントをバインド
// Bind button click events
void UStartOverlay::NativeConstruct()
{
    if (PlayButton)
    {
        PlayButton->OnClicked.AddDynamic(this, &UStartOverlay::StartGameButton);
    }
    if (QuitButton)
    {
        QuitButton->OnClicked.AddDynamic(this, &UStartOverlay::QuitGameButton);
    }
}

// プレイ_始I理
// Handle Play button click: start game
void UStartOverlay::StartGameButton()
{
    // オ`バ`レイを非表示
    // Remove the overlay widget
    RemoveFromParent();

    // プレイヤ`コントロ`ラを取得し、ゲ`ムを再_
    // Get player controller and unpause the game
    if (APlayerController* PlayerController = GetWorld()->GetFirstPlayerController())
    {
        PlayerController->SetPause(false);
        PlayerController->SetShowMouseCursor(false);
        PlayerController->SetInputMode(FInputModeGameOnly());
    }

    // F在のレベルを再iみzみ
    // Reload current level to start fresh
    UGameplayStatics::OpenLevel(this, FName(*GetWorld()->GetName()), false);
}

// K了I理
// Handle Quit button click: exit game
void UStartOverlay::QuitGameButton()
{
    // オ`バ`レイを非表示
    // Remove the overlay widget
    RemoveFromParent();

    // ゲ`ムをK了
    // Quit the game
    if (APlayerController* PlayerController = GetWorld()->GetFirstPlayerController())
    {
        UKismetSystemLibrary::QuitGame(this, PlayerController, EQuitPreference::Quit, false);
    }
}
